### ISSUE TITLE
Add unit tests script

### ISSUE THREAD

**Issue by junyada100** [VaultExpress/vault-express#12]

**Comment by junyada100** [comment]
Just initial tests script is enough for this issue scope

**Comment by thismarcoantonio** [comment]
I wanna help in this project, someone is working in this issue at the moment?

**Comment by junyada100** [comment]
not yet, welcome on board ^ ^

**Comment by junyada100** [comment]
We have a chat room on gitter (https://gitter.im), i've tried to add you but look like you are not on it. let me know if you wanna join that

**Comment by thismarcoantonio** [comment]
Yeah sure
