### ISSUE TITLE
Add cookie consent

### ISSUE THREAD

**Issue by junyada100** [VaultExpress/vault-express#15]

**Comment by willybeans** [comment]
Are you interested in using an this: https://github.com/insites/cookieconsent/

if so ill gladly add it to the project.

**Comment by junyada100** [comment]
sure, that's a good one, i think

**Comment by willybeans** [comment]
Jun, 
 Where do you want me to put this JS file? Inside the pages directory? Make a new directory for it? What is your preference?

We can use it as a dependency, or we can use a CDN. I assume you would want to have it as a dependency incase the CDN stops working in the future? Just thought i would confirm with you first.

**Comment by junyada100** [comment]
Close by #74
